// <auto-generated />
using System;
using System.Collections.Generic;
using DiceRoller.Operative.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiceRoller.Operative.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OperativeDbContext))]
    [Migration("20261008131021_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiceRoller.Operative.Domain.DiceRolls.DiceRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RolledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sum")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("CAST([Die1] AS int) + CAST([Die2] AS int)", true);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Die1", "DiceRoller.Operative.Domain.DiceRolls.DiceRoll.Die1#DieValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("Value")
                                .HasColumnType("tinyint")
                                .HasColumnName("Die1");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Die2", "DiceRoller.Operative.Domain.DiceRolls.DiceRoll.Die2#DieValue", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<byte>("Value")
                                .HasColumnType("tinyint")
                                .HasColumnName("Die2");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RolledAtUtc")
                        .HasDatabaseName("IX_DiceRolls_UserId_RolledAtUtc");

                    b.HasIndex("UserId", "Sum", "RolledAtUtc")
                        .HasDatabaseName("IX_DiceRolls_UserId_Sum_RolledAtUtc");

                    b.ToTable("DiceRolls", null, t =>
                        {
                            t.HasCheckConstraint("CK_DiceRolls_Die1", "[Die1] BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_DiceRolls_Die2", "[Die2] BETWEEN 1 AND 6");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
